site_name: AI Frameworks

use_directory_urls: false

nav:
  - Home: index.md
  - Courses:
    - Course introduction: introduction.md
    - Introduction to Git: git_intro.md
    - Text:
      - Text Cleaning and Vectorization: text1.md
      - Words embedding: text2.md
      - Recurrent Network: text3.md
    - Development tools for Data Scientist: 
      - Virtual environments, Github Repositories and Scripts: dev.md
      - Introduction to GCloud: gcloud.md
      - Introduction to Docker: docker.md
    - Introduction to deep Reinforcement learning:
      - Q-learning: q_learning.md
      - Policy Gradient: policy_gradient.md
    - Recommender systems: rec_sys.md
  - Schedule: schedule.md
  - Evaluation: evaluation.md
#theme: slate
theme:
  name: 'spacelab'
  logo: img/logo-insa.jpg
  favicon: img/favicon.ico
  